# python -m apps.main.generate config=apps/main/configs/eval.yaml
# torchrun --standalone --nnodes 1 --nproc-per-node 4 -m apps.main.eval config=apps/main/configs/eval.yam
name: "debug_evals"
ckpt_dir:  /mnt/data/dump/ImageNet_1B_BaseLine_256_Flux_LLAMA_Pre_Train/checkpoints/0000030000/
dump_dir:  /mnt/data/dump/ImageNet_1B_BaseLine_256_Flux_LLAMA_Pre_Train/checkpoints/0000030000/
sample_num: 1000
generator:
  guidance_scale: 2.0
  dtype: bf16
  resolution: 256
  show_progress: False
  inference_steps: 100

eval_data:
    root_dir: '/mnt/data/imagenet'
    batch_size: 32
    image_size: 256
    num_workers: 8
    split: 'validation'