name: sora
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgomp=14.1.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.46.1=hadc24fc_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - ncurses=6.5=he02047a_1
  - openssl=3.3.2=hb9d3cd8_0
  - pip=24.2=pyh8b19718_1
  - python=3.9.20=h13acc7a_0_cpython
  - readline=8.2=h8228510_1
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.2.1
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.0
      - apex==0.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - asttokens==2.4.1
      - attrs==24.2.0
      - av==13.0.0
      - bcrypt==4.2.0
      - beartype==0.18.5
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.43.3
      - black==24.8.0
      - blessed==1.20.0
      - blinker==1.8.2
      - boto3==1.35.45
      - botocore==1.35.45
      - braceexpand==0.1.7
      - bracex==2.5.post1
      - build==1.2.2.post1
      - certifi==2024.8.30
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - clarabel==0.9.0
      - click==8.1.7
      - clip==1.0
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - colossalai==0.4.0
      - comm==0.2.2
      - configargparse==1.7
      - contexttimer==0.3.3
      - contourpy==1.3.0
      - cryptography==43.0.1
      - cupy-cuda12x==13.3.0
      - cvxpy==1.5.3
      - cycler==0.12.1
      - dash==2.18.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.8.5
      - decorator==4.4.2
      - decord==0.6.0
      - deprecated==1.2.14
      - detectron2==0.6
      - diffusers==0.32.0.dev0
      - dill==0.3.8
      - distlib==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - ecos==2.0.14
      - einops==0.8.0
      - einops-exts==0.0.4
      - einx==0.3.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fabric==3.2.2
      - fastapi==0.115.0
      - fastjsonschema==2.20.0
      - fastrlock==0.8.2
      - ffmpeg-python==0.2.0
      - ffmpy==0.4.0
      - filelock==3.16.1
      - fire==0.7.0
      - flash-attn==2.6.3
      - flask==3.0.3
      - flow-vis==0.1
      - fonttools==4.53.1
      - freetype-py==2.5.1
      - frozendict==2.4.6
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - ftfy==6.2.3
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - galore-torch==1.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google==3.0.0
      - gpustat==1.1.1
      - gradio==4.44.0
      - gradio-client==1.3.0
      - grpcio==1.66.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - huggingface-hub==0.25.0
      - hydra-core==1.3.2
      - identify==2.6.1
      - idna==3.10
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - imgaug==0.4.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - invoke==2.2.0
      - iopath==0.1.9
      - ipdb==0.13.13
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jiter==0.5.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kagglehub==0.3.5
      - kapture==1.1.10
      - kapture-localization==1.1.10
      - kiwisolver==1.4.7
      - langdetect==1.0.9
      - latex2mathml==3.77.0
      - lazy-loader==0.4
      - lietorch==0.2
      - lingua-language-detector==2.0.2
      - llvmlite==0.43.0
      - lmdb==1.5.1
      - loguru==0.7.3
      - lpips==0.1.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markdown2==2.5.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.2
      - minio==7.2.9
      - mmcv==2.1.0
      - mmdet==3.1.0
      - mmengine==0.10.5
      - mmocr==1.0.1
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mypy-extensions==1.0.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nodeenv==1.9.1
      - numba==0.60.0
      - numpy==1.26.4
      - numpy-quaternion==2023.0.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - open3d==0.18.0
      - openai==1.47.0
      - opencv-python==4.9.0.80
      - opensora==1.2.0
      - orjson==3.10.7
      - osqp==0.6.7.post3
      - packaging==24.1
      - pandarallel==1.6.5
      - pandas==2.2.3
      - parameterized==0.9.0
      - paramiko==3.5.0
      - parso==0.8.4
      - pathspec==0.12.1
      - peft==0.12.0
      - pexpect==4.9.0
      - piexif==1.1.3
      - pillow==10.3.0
      - pillow-heif==0.20.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - plumbum==1.8.3
      - portalocker==2.10.1
      - poselib==2.0.4
      - pre-commit==3.8.0
      - proglog==0.1.10
      - prompt-toolkit==3.0.47
      - protobuf==5.28.2
      - psutil==5.9.8
      - ptvsd==4.3.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pyclipper==1.3.0.post5
      - pycocotools==2.0.8
      - pycolmap==0.6.1
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pyglet==1.5.29
      - pygments==2.18.0
      - pynacl==1.5.0
      - pyopengl==3.1.0
      - pyparsing==3.1.4
      - pyproject-hooks==1.2.0
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.10
      - pytorch3d==0.7.8
      - pytorchvideo==0.1.5
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - qdldl==0.1.7.post4
      - rapidfuzz==3.10.0
      - ray==2.36.0
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.3
      - retrying==1.3.4
      - rich==13.8.1
      - roma==1.5.1
      - rotary-embedding-torch==0.5.3
      - rpds-py==0.20.0
      - rpyc==6.0.0
      - ruff==0.6.7
      - s3transfer==0.10.3
      - safetensors==0.4.5
      - scenedetect==0.6.5
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - scs==3.2.7
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.14.0
      - setproctitle==1.3.3
      - setuptools==68.2.2
      - shapely==2.0.6
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soundfile==0.12.1
      - soupsieve==2.6
      - spaces==0.30.2
      - stack-data==0.6.3
      - starlette==0.38.6
      - svgwrite==1.4.3
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - timeout-decorator==0.5.0
      - timm==0.9.16
      - tokenizers==0.15.2
      - tomli==2.0.1
      - tomlkit==0.12.0
      - torch==2.2.2
      - torchdata==0.10.0
      - torchvision==0.17.2
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.39.3
      - trimesh==4.5.2
      - triton==2.2.0
      - typer==0.12.5
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.3
      - uvicorn==0.29.0
      - virtualenv==20.26.5
      - wandb==0.18.1
      - wavedrom==2.0.3.post3
      - wcmatch==10.0
      - wcwidth==0.2.13
      - webdataset==0.2.100
      - websockets==12.0
      - webvtt-py==0.5.1
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - xformers==0.0.25.post1
      - yacs==0.1.8
      - yapf==0.40.2
      - yt-dlp==2024.12.6
      - zipp==3.20.2
